apiVersion: v1
kind: Pod
metadata:
  name: go-product-builder-pod
  labels:
    app.kubernetes.io/name: go-product-builder-pod
spec:
  containers:
    - name: go-product-builder-pod
      image: quinncaverly/go-product-builder-pod:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-product-builder-service
spec:
  selector:
    app.kubernetes.io/name: go-product-builder-pod
  ports:
    - name: rcp
      protocol: TCP
      port: 8080
      targetPort: 8080
