apiVersion: v1
kind: PersistentVolume
metadata:
  name: images-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /data/forward/images
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - quinn-caverly-ubuntu

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: images-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  volumeName: images-pv
  storageClassName: manual
