// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ColorContainer struct {
	ColorName   string   `json:"ColorName"`
	DateScraped string   `json:"DateScraped"`
	ImageBytes  []string `json:"ImageBytes"`
}

type ProductDisplayContainer struct {
	Up              *UniqueProduct    `json:"Up"`
	ColorContainers []*ColorContainer `json:"ColorContainers,omitempty"`
}

type UniqueProduct struct {
	ID             string `json:"Id"`
	Brand          string `json:"Brand"`
	Name           string `json:"Name"`
	URLOnBrandSite string `json:"UrlOnBrandSite"`
	Price          string `json:"Price"`
	Description    string `json:"Description"`
	ClothingType   string `json:"ClothingType"`
}
